# Generated by Django 2.2.2 on 2019-06-21 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='authos',
            new_name='author',
        ),
    ]
